# AUTOSCRIPT NAME: EX2PRFIRSTSAVE
# CREATEDDATE: 2013-10-23 09:08:42
# CREATEDBY: UFQJ
# CHANGEDATE: 2017-05-10 10:11:33
# CHANGEBY: UT76
# SCRIPTLANGUAGE: jython
# STATUS: Active

# set source of record creation for use in escalations and workflow
#INC000001158045 Proc PR/PO Project Number Populated 
#INC000001210363 if created by reorder set required delivery date to sysdate + leadtime

from psdi.mbo import MboConstants 
from java.util import Date
from java.util import Calendar

v_isReorder=0
cal=Calendar.getInstance()

if onadd:
    if not mbo.isNull("sourcesysid"):     # if from (EMT) interface, use source system
        mbo.setValue("ex2prsource", mbo.getString("sourcesysid"))
    else:                              # if the app is set, use that
        mbo.setValue("ex2prsource", app)
    if mbo.isNull("ex2prsource"):       # if still not set (no interface, app vbl not populated), assume reorder -- check description to make sure
        if mbo.getString("DESCRIPTION")[0:21] ==   "Generated by reorder ":
            mbo.setValue("ex2prsource", "Reorder")
            v_isReorder=1
        else:
            mbo.setValue("ex2prsource", "Unknown")

# set buyer from contrat buyer - need this code here for reorder situation
    if mbo.getString("ex2prsource") == "Reorder" :
        contrSet = mbo.getMboSet("CONTRACTREF")
        if contrSet.count() > 0:
            contrmbo = contrSet.getMbo(0)
            if contrmbo and mbo.isNull("ex2buyer"):
                mbo.setValue("ex2buyer",contrmbo.getString("purchaseagent"),MboConstants.NOACCESSCHECK)


#INC000001158045 & INC000001210363

    prlinelset = mbo.getMboSet("PRLINE")
    num1 =  prlinelset.count()
    if prlinelset.count() > 0:
           for s in range (num1):
                prlinembo = prlinelset.getMbo(s)
                GLDEBITACCT = prlinembo.getString("GLDEBITACCT")
                if GLDEBITACCT is not None:
                    project=GLDEBITACCT[23:31]
                    if project != '????????' :
                        prlinembo.setValue("EX2PROJECT",project,MboConstants.NOACCESSCHECK)
                if v_isReorder==1:
                    cal.setTime(Date())
                    ivMboSet = prlinembo.getMboSet("INVENTORY")
                    if ivMboSet.count() > 0: 
                        ivMbo = ivMboSet.getMbo(0)
                        cal.add(Calendar.DATE, +ivMbo.getInt("DELIVERYTIME"))
                        prlinembo.setValue("REQDELIVERYDATE", cal.getTime(), MboConstants.NOACCESSCHECK)
                        v_time = cal.getTime()